name: Bass-UI Continuous Intergration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - run: pnpm chromatic
