concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Bass-UI Continuous Intergration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm --filter "@repo/ui" exec playwright install chromium --with-deps

      - name: run lint
        run: pnpm lint

      - name: run test
        run: pnpm test --filter "...[origin/main]"

      - name: run build
        run: pnpm build --filter "...[origin/main]"

      - name: run chromatic
        run: pnpm --filter "@repo/ui" chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
